# FastAPI 应用配置文件
[app]
# 应用基本信息
name = "PDF处理服务"
version = "0.1.0"
description = "基于FastAPI的PDF文档处理服务"
debug = true

# 服务器配置
[server]
host = "0.0.0.0"
port = 6677
reload = true
workers = 1
log_level = "info"

# 数据库配置（预留）
[database]
url = "sqlite:///./data/app.db"
echo = false

# 文件存储配置
[storage]
# PDF文件存储路径
pdf_upload_path = "./data/uploads"
# 处理结果存储路径
result_path = "."
# 最大文件大小 (MB)
max_file_size = 50

# 日志配置
[logging]
level = "INFO"
format = "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
file_path = "./logs/app.log"
rotation = "1 day"
retention = "30 days"

# API配置
[api]
# API前缀
prefix = "/api/v1"
# 跨域配置
cors_origins = ["*"]
cors_methods = ["GET", "POST", "PUT", "DELETE"]
cors_headers = ["*"]

# 安全配置
[security]
# JWT密钥（生产环境应使用环境变量）
secret_key = "your-secret-key-here"
# Token过期时间（小时）
token_expire_hours = 24

# 外部服务配置
[external_services]
# OpenAI配置
openai_api_key = ""
openai_base_url = "https://api.openai.com/v1"
# ChromaDB配置
chroma_host = "localhost"
chroma_port = 8000
# 视觉语言模型API配置
vl_api_url = "http://example.com/api/upload"
# VLLM框架API配置
vllm_api_url = "http://localhost:58123/v1/chat/completions"
# 向量模型配置
embedding_model_path = "/bge-large-zh-v1.5" 